#!/usr/bin/env python3
"""Generate src/data/definitions.json from a compact term list."""

import json
from pathlib import Path

# (id, chapterId, term, definition, example, related, aliases)
TERMS = [
    # Chapter 1
    ("economics", "ch1", "Economics",
     "The study of how individuals, firms, and societies choose to allocate scarce resources among competing uses.",
     "A government deciding how much of its budget to spend on schools versus roads is an economic choice.",
     ["scarcity", "opportunity-cost", "microeconomics", "macroeconomics"],
     []),
    ("scarcity", "ch1", "Scarcity",
     "The condition that wants exceed the resources available to satisfy them, so every choice requires a trade-off.",
     "There is only so much time in a day, so studying more economics means less time for something else.",
     ["opportunity-cost", "trade-off", "economics"],
     []),
    ("opportunity-cost", "ch1", "Opportunity cost",
     "The value of the next-best alternative given up when a choice is made.",
     "The opportunity cost of a concert ticket is the dinner, or the savings, you could have had with that same money and evening.",
     ["trade-off", "scarcity", "sunk-cost"],
     []),
    ("trade-off", "ch1", "Trade-off",
     "A situation in which having more of one thing requires having less of another.",
     "A society that produces more military goods typically produces fewer consumer goods.",
     ["opportunity-cost", "production-possibilities-frontier", "scarcity"],
     []),
    ("incentives", "ch1", "Incentives",
     "Rewards or penalties that shape people's choices. People usually respond to incentives in predictable ways.",
     "A tax on sugary drinks raises their price and typically reduces the quantity demanded.",
     ["rational-choice", "marginal-analysis"],
     []),
    ("marginal-analysis", "ch1", "Marginal analysis",
     "Comparing the additional benefit of one more unit of an activity with its additional cost.",
     "A firm hires one more worker only if that worker's extra revenue covers the extra wage.",
     ["marginal-benefit", "marginal-cost", "rational-choice"],
     ["thinking at the margin"]),
    ("marginal-benefit", "ch1", "Marginal benefit",
     "The extra benefit obtained from consuming or producing one additional unit.",
     "The first slice of pizza is worth more to you than the fourth.",
     ["marginal-cost", "diminishing-marginal-utility", "marginal-analysis"],
     ["MB"]),
    ("marginal-cost", "ch1", "Marginal cost",
     "The extra cost of producing or doing one additional unit.",
     "The cost of staying open one more hour is the extra wages and utilities for that hour.",
     ["marginal-benefit", "marginal-analysis", "mc"],
     ["MC"]),
    ("rational-choice", "ch1", "Rational choice",
     "Choosing the option that the decision maker believes will best achieve their objectives, given constraints and information.",
     "A commuter picks the subway over a taxi when the time and money trade-off favors the subway.",
     ["incentives", "opportunity-cost", "marginal-analysis"],
     ["rationality"]),
    ("positive-statement", "ch1", "Positive statement",
     "A claim about what is, was, or will be that can be tested with evidence. It is about facts, not values.",
     "\"Raising the minimum wage will reduce teen employment\" is a positive claim, whether it turns out true or false.",
     ["normative-statement"],
     []),
    ("normative-statement", "ch1", "Normative statement",
     "A claim about what ought to be. It rests on values and cannot be settled by data alone.",
     "\"The minimum wage should be higher so work pays a living wage\" is a normative judgment.",
     ["positive-statement"],
     []),
    ("ceteris-paribus", "ch1", "Ceteris paribus",
     "Latin for \"other things equal.\" Economists hold other variables constant to isolate one relationship.",
     "The law of demand says that, ceteris paribus, a higher price reduces quantity demanded.",
     ["law-of-demand", "demand-curve"],
     ["other things equal"]),
    ("efficiency", "ch1", "Efficiency",
     "Getting the most value from scarce resources. An outcome is efficient when no one can be made better off without making someone else worse off.",
     "If leftover bread is thrown away while people nearby want it, the allocation is inefficient.",
     ["equity", "total-surplus", "pareto-improvement"],
     ["allocative efficiency"]),
    ("equity", "ch1", "Equity",
     "Fairness in the distribution of economic benefits. Equity is a value judgment and can conflict with efficiency.",
     "A progressive income tax can increase equity while changing work and investment incentives.",
     ["efficiency", "normative-statement"],
     ["fairness"]),
    ("microeconomics", "ch1", "Microeconomics",
     "The study of individual decision makers — households, firms, and specific markets — and the prices that coordinate them.",
     "How a coffee shop sets prices and how students choose majors are micro questions.",
     ["macroeconomics", "economics"],
     ["micro"]),
    ("macroeconomics", "ch1", "Macroeconomics",
     "The study of the economy as a whole: total output, unemployment, inflation, growth, and policy.",
     "Why the unemployment rate rose last year is a macro question.",
     ["microeconomics", "gdp", "inflation"],
     ["macro"]),
    ("factors-of-production", "ch1", "Factors of production",
     "The inputs used to produce goods and services, usually grouped as land, labor, capital, and entrepreneurship.",
     "A bakery uses a kitchen (capital), a baker (labor), flour (land/materials), and an owner who organizes them.",
     ["production-function", "physical-capital", "human-capital"],
     ["inputs", "resources"]),
    ("production-possibilities-frontier", "ch1", "Production possibilities frontier",
     "A curve showing the maximum combinations of two goods an economy can produce with given resources and technology. Points on the frontier are efficient; inside are inefficient; outside are unattainable.",
     "A country that uses all resources can have more hospitals only by having fewer other buildings.",
     ["opportunity-cost", "trade-off", "increasing-opportunity-cost", "efficiency"],
     ["PPF", "PPC", "production possibilities curve"]),
    ("increasing-opportunity-cost", "ch1", "Increasing opportunity cost",
     "The idea that as you produce more of one good, you give up increasingly larger amounts of the other, because resources are not equally suited to every use. This bows the PPF outward.",
     "The first acres used for wheat may be perfect farmland; later acres may have been much better as orchards.",
     ["production-possibilities-frontier", "opportunity-cost"],
     ["law of increasing opportunity cost"]),
    ("sunk-cost", "ch1", "Sunk cost",
     "A cost that has already been incurred and cannot be recovered. Rational decisions ignore sunk costs and look only at future costs and benefits.",
     "You already paid for a nonrefundable ticket. Whether you go should depend on tonight's alternatives, not the sunk price.",
     ["opportunity-cost", "rational-choice", "marginal-analysis"],
     []),
    ("pareto-improvement", "ch1", "Pareto improvement",
     "A change that makes at least one person better off without making anyone worse off.",
     "Reallocating an unused classroom to a waitlisted seminar can be a Pareto improvement.",
     ["efficiency"],
     []),

    # Chapter 2
    ("absolute-advantage", "ch2", "Absolute advantage",
     "The ability to produce a good using fewer inputs, or to produce more output with the same inputs, than another producer.",
     "If Pat types faster and cooks faster than Sam, Pat has an absolute advantage in both tasks.",
     ["comparative-advantage", "specialization"],
     []),
    ("comparative-advantage", "ch2", "Comparative advantage",
     "The ability to produce a good at a lower opportunity cost than another producer. Comparative advantage, not absolute advantage, is the basis for mutually beneficial trade.",
     "Even if a lawyer types faster than a secretary, the lawyer's opportunity cost of typing is higher, so the secretary has the comparative advantage in typing.",
     ["absolute-advantage", "opportunity-cost", "gains-from-trade", "specialization"],
     []),
    ("specialization", "ch2", "Specialization",
     "Concentrating production on the goods or tasks for which a person or country has a comparative advantage.",
     "Portugal specializing in wine and England in cloth is the classic textbook example.",
     ["comparative-advantage", "gains-from-trade"],
     []),
    ("gains-from-trade", "ch2", "Gains from trade",
     "The extra output or extra utility that parties obtain by specializing and exchanging, compared with producing only for themselves.",
     "Two roommates who split cooking and cleaning according to comparative advantage finish both chores faster.",
     ["comparative-advantage", "specialization", "terms-of-trade"],
     []),
    ("terms-of-trade", "ch2", "Terms of trade",
     "The rate at which one good is exchanged for another. Mutually beneficial terms of trade lie between the two parties' opportunity costs.",
     "If one country gives up 1 cloth for 2 wine and the other gives up 1 cloth for 4 wine, they can trade at 1 cloth for 3 wine and both gain.",
     ["gains-from-trade", "comparative-advantage"],
     []),
    ("imports", "ch2", "Imports",
     "Goods and services purchased from foreign producers and consumed domestically.",
     "A U.S. household buying a phone assembled abroad is importing.",
     ["exports", "net-exports", "autarky"],
     []),
    ("exports", "ch2", "Exports",
     "Goods and services produced domestically and sold to buyers in other countries.",
     "Brazilian coffee sold in Europe is an export for Brazil.",
     ["imports", "net-exports"],
     []),
    ("autarky", "ch2", "Autarky",
     "A situation in which a country or person does not trade with others and consumes only what it produces.",
     "A household that grows all its own food and never shops is living in autarky.",
     ["gains-from-trade", "imports", "exports"],
     []),
    ("interdependence", "ch2", "Interdependence",
     "The reliance of people and countries on one another for goods, services, and inputs that results from specialization and trade.",
     "Modern car production depends on parts and software from many countries.",
     ["specialization", "gains-from-trade"],
     []),

    # Chapter 3
    ("market", "ch3", "Market",
     "A group of buyers and sellers of a particular good or service, and the arrangements through which they trade.",
     "The market for used laptops includes campus listings, shops, and online platforms.",
     ["competitive-market", "equilibrium"],
     []),
    ("competitive-market", "ch3", "Competitive market",
     "A market with many buyers and sellers of a nearly identical product, so that no single trader can influence the price.",
     "Wholesale wheat is closer to a competitive market than the market for a patented drug.",
     ["market", "price-taker", "perfect-competition"],
     ["perfectly competitive market"]),
    ("demand", "ch3", "Demand",
     "The relationship between the price of a good and the quantity buyers are willing and able to purchase, other things equal.",
     "At lower coffee prices, more cups are demanded each morning.",
     ["quantity-demanded", "law-of-demand", "demand-curve"],
     []),
    ("quantity-demanded", "ch3", "Quantity demanded",
     "The amount of a good buyers want to buy at a specific price. A price change moves quantity demanded along the demand curve.",
     "If the price of apples falls from $2 to $1, quantity demanded might rise from 4 to 7 pounds.",
     ["demand", "law-of-demand"],
     ["Qd"]),
    ("law-of-demand", "ch3", "Law of demand",
     "Other things equal, when the price of a good rises, the quantity demanded falls, and when the price falls, quantity demanded rises.",
     "Concert tickets that get more expensive usually sell fewer seats.",
     ["demand", "quantity-demanded", "ceteris-paribus"],
     []),
    ("demand-curve", "ch3", "Demand curve",
     "A graph of the demand relationship, with price on the vertical axis and quantity on the horizontal axis. It usually slopes down.",
     "A city transit map of fares versus daily riders is a demand curve.",
     ["demand", "substitutes", "complements"],
     []),
    ("substitutes", "ch3", "Substitutes",
     "Goods that can take each other's place. A rise in the price of one increases demand for the other.",
     "Butter and margarine are substitutes for many cooks.",
     ["complements", "cross-price-elasticity", "demand"],
     []),
    ("complements", "ch3", "Complements",
     "Goods that are used together. A rise in the price of one decreases demand for the other.",
     "Printers and ink cartridges are complements.",
     ["substitutes", "cross-price-elasticity", "demand"],
     []),
    ("normal-good", "ch3", "Normal good",
     "A good for which demand rises when income rises.",
     "Restaurant meals are a normal good for most households.",
     ["inferior-good", "income-elasticity"],
     []),
    ("inferior-good", "ch3", "Inferior good",
     "A good for which demand falls when income rises.",
     "Instant noodles may be inferior if people switch to fresher food as income grows.",
     ["normal-good", "income-elasticity"],
     []),
    ("supply", "ch3", "Supply",
     "The relationship between the price of a good and the quantity sellers are willing and able to sell, other things equal.",
     "Higher wheat prices lead farmers to plant more wheat.",
     ["quantity-supplied", "law-of-supply", "supply-curve"],
     []),
    ("quantity-supplied", "ch3", "Quantity supplied",
     "The amount of a good sellers want to sell at a specific price. A price change moves quantity supplied along the supply curve.",
     "If tablet prices rise, existing factories may run extra shifts and raise quantity supplied.",
     ["supply", "law-of-supply"],
     ["Qs"]),
    ("law-of-supply", "ch3", "Law of supply",
     "Other things equal, when the price of a good rises, the quantity supplied rises, and when the price falls, quantity supplied falls.",
     "A surge in avocado prices encourages more growers to harvest and ship avocados.",
     ["supply", "quantity-supplied"],
     []),
    ("supply-curve", "ch3", "Supply curve",
     "A graph of the supply relationship. It usually slopes up because higher prices draw out more production.",
     "An oil-field chart of price versus barrels offered is a supply curve.",
     ["supply", "input-prices"],
     []),
    ("input-prices", "ch3", "Input prices",
     "The prices of factors and materials used to produce a good. Higher input prices shift supply left; lower input prices shift it right.",
     "A jump in steel prices shifts the supply of cars leftward.",
     ["supply", "factors-of-production"],
     ["factor prices"]),
    ("equilibrium", "ch3", "Equilibrium",
     "The price and quantity at which quantity demanded equals quantity supplied. There is no tendency for price to change until something shifts demand or supply.",
     "If 1,000 tickets are demanded and supplied at $40, the concert market is in equilibrium.",
     ["surplus", "shortage", "market-clearing-price"],
     ["market equilibrium"]),
    ("market-clearing-price", "ch3", "Market-clearing price",
     "The equilibrium price: the price that clears the market by equating quantity demanded and quantity supplied.",
     "Auction prices often move until the last unsold item finds a buyer.",
     ["equilibrium"],
     ["market clearing price"]),
    ("surplus", "ch3", "Surplus",
     "A situation in which quantity supplied exceeds quantity demanded at the current price. Price tends to fall.",
     "Unsold winter coats in March are a surplus; stores mark them down.",
     ["shortage", "equilibrium", "price-floor"],
     ["excess supply"]),
    ("shortage", "ch3", "Shortage",
     "A situation in which quantity demanded exceeds quantity supplied at the current price. Price tends to rise.",
     "Sold-out festival tickets at the printed price are a shortage.",
     ["surplus", "equilibrium", "price-ceiling"],
     ["excess demand"]),

    # Chapter 4
    ("elasticity", "ch4", "Elasticity",
     "A unit-free measure of how much one variable responds to a change in another, usually as a percentage change over a percentage change.",
     "If a 10% price cut raises quantity demanded 20%, demand elasticity is 2.",
     ["price-elasticity-of-demand", "price-elasticity-of-supply"],
     []),
    ("price-elasticity-of-demand", "ch4", "Price elasticity of demand",
     "The percentage change in quantity demanded divided by the percentage change in price. Economists often report it as a positive number (absolute value).",
     "If price rises 5% and quantity demanded falls 15%, elasticity is 3.",
     ["elastic-demand", "inelastic-demand", "total-revenue-test"],
     ["PED", "own-price elasticity"]),
    ("elastic-demand", "ch4", "Elastic demand",
     "Demand is elastic when the price elasticity is greater than 1: quantity changes by a larger percentage than price.",
     "Demand for a particular brand of cereal is often elastic because many brands are close substitutes.",
     ["inelastic-demand", "unit-elastic", "price-elasticity-of-demand"],
     []),
    ("inelastic-demand", "ch4", "Inelastic demand",
     "Demand is inelastic when the price elasticity is less than 1: quantity changes by a smaller percentage than price.",
     "Demand for insulin is highly inelastic because there are few substitutes.",
     ["elastic-demand", "perfectly-inelastic", "price-elasticity-of-demand"],
     []),
    ("unit-elastic", "ch4", "Unit elastic",
     "A response in which the percentage change in quantity equals the percentage change in price, so elasticity equals 1.",
     "If a 10% price rise cuts quantity demanded by 10%, demand is unit elastic.",
     ["elastic-demand", "inelastic-demand"],
     ["unit elastic demand", "unitary elastic"]),
    ("perfectly-elastic", "ch4", "Perfectly elastic",
     "Elasticity is infinite: buyers or sellers will trade any amount at one price and nothing at a slightly worse price. The curve is horizontal.",
     "A small wheat farm in a huge market faces a nearly perfectly elastic demand at the market price.",
     ["perfectly-inelastic", "price-taker"],
     []),
    ("perfectly-inelastic", "ch4", "Perfectly inelastic",
     "Elasticity is zero: quantity does not change when price changes. The curve is vertical.",
     "A unique painting has a perfectly inelastic supply: there is only one of it.",
     ["perfectly-elastic", "inelastic-demand"],
     []),
    ("total-revenue-test", "ch4", "Total revenue test",
     "If price and total revenue move in opposite directions, demand is elastic. If they move together, demand is inelastic. If revenue is unchanged, demand is unit elastic.",
     "A fare hike that fills the register with more money means demand for those rides is inelastic.",
     ["price-elasticity-of-demand", "elastic-demand"],
     []),
    ("income-elasticity", "ch4", "Income elasticity of demand",
     "The percentage change in quantity demanded divided by the percentage change in income. Positive for normal goods, negative for inferior goods.",
     "If income rises 10% and restaurant meals rise 15%, income elasticity is 1.5.",
     ["normal-good", "inferior-good"],
     ["income elasticity"]),
    ("cross-price-elasticity", "ch4", "Cross-price elasticity of demand",
     "The percentage change in quantity demanded of one good divided by the percentage change in the price of another. Positive for substitutes, negative for complements.",
     "If tea prices rise 10% and coffee demand rises 4%, the cross-price elasticity is 0.4.",
     ["substitutes", "complements"],
     ["cross price elasticity", "XED"]),
    ("price-elasticity-of-supply", "ch4", "Price elasticity of supply",
     "The percentage change in quantity supplied divided by the percentage change in price. Supply is more elastic when firms can expand output easily.",
     "Beachfront land has inelastic supply; factory-made mugs have more elastic supply.",
     ["elasticity", "supply"],
     ["PES"]),
    ("determinants-of-elasticity", "ch4", "Determinants of demand elasticity",
     "Demand is more elastic when there are close substitutes, the good is a luxury, the time horizon is long, or the good takes a large share of the budget.",
     "Gasoline demand is more elastic over several years than over a single week.",
     ["price-elasticity-of-demand", "elastic-demand"],
     []),

    # Chapter 5
    ("utility", "ch5", "Utility",
     "A measure of the satisfaction or well-being a person gets from consuming goods and services.",
     "A rainy-day movie may give you more utility than another hour of chores.",
     ["marginal-utility", "diminishing-marginal-utility"],
     []),
    ("marginal-utility", "ch5", "Marginal utility",
     "The extra utility from consuming one more unit of a good.",
     "The first glass of water after a run has high marginal utility; the fifth does not.",
     ["utility", "diminishing-marginal-utility"],
     ["MU"]),
    ("diminishing-marginal-utility", "ch5", "Diminishing marginal utility",
     "The principle that extra utility from each additional unit of a good eventually falls, holding other consumption fixed.",
     "The tenth cookie in a sitting is less satisfying than the first.",
     ["marginal-utility", "utility", "marginal-benefit"],
     ["DMU", "law of diminishing marginal utility"]),
    ("budget-constraint", "ch5", "Budget constraint",
     "The limit on consumption bundles a household can afford, given income and prices. Its slope is the relative price of the two goods.",
     "With $20, $2 tacos and $4 sodas, you can buy at most 10 tacos or 5 sodas, or mixtures on the line between them.",
     ["indifference-curve", "opportunity-cost"],
     ["budget line"]),
    ("indifference-curve", "ch5", "Indifference curve",
     "A curve showing bundles that give a consumer the same utility. Higher curves are better if more is preferred to less.",
     "You might be equally happy with 2 concerts and 8 meals or 3 concerts and 5 meals.",
     ["mrs", "budget-constraint", "utility"],
     []),
    ("mrs", "ch5", "Marginal rate of substitution",
     "The rate at which a consumer is willing to trade one good for another while staying equally happy. It is the slope of an indifference curve.",
     "If you will give up 2 coffees for 1 extra pastry and feel no worse, your MRS is 2 coffees per pastry.",
     ["indifference-curve", "opportunity-cost"],
     ["MRS"]),
    ("willingness-to-pay", "ch5", "Willingness to pay",
     "The maximum amount a buyer will pay for a unit of a good. It measures the buyer's marginal benefit.",
     "If you would pay up to $12 for a book priced at $8, your consumer surplus on that book is $4.",
     ["consumer-surplus", "marginal-benefit"],
     ["WTP"]),
    ("consumer-surplus", "ch5", "Consumer surplus",
     "The difference between what buyers are willing to pay and what they actually pay, summed across units purchased.",
     "A fan willing to pay $80 who buys a $50 ticket enjoys $30 of consumer surplus.",
     ["producer-surplus", "total-surplus", "willingness-to-pay"],
     ["CS"]),
    ("producer-surplus", "ch5", "Producer surplus",
     "The difference between the price sellers receive and the minimum they would have accepted (their marginal cost), summed across units sold.",
     "A musician who would play for $200 and is paid $350 earns $150 of producer surplus.",
     ["consumer-surplus", "total-surplus", "marginal-cost"],
     ["PS"]),
    ("total-surplus", "ch5", "Total surplus",
     "Consumer surplus plus producer surplus. In a well-functioning competitive market with no externalities, equilibrium maximizes total surplus.",
     "A street market that matches willing buyers and sellers raises total surplus compared with no trade.",
     ["consumer-surplus", "producer-surplus", "efficiency", "deadweight-loss"],
     ["social surplus", "total welfare"]),
    ("reservation-price", "ch5", "Reservation price",
     "The cutoff price at which a buyer is just willing to buy, or a seller is just willing to sell.",
     "A seller's reservation price for a used bike might be $90; below that they keep it.",
     ["willingness-to-pay", "producer-surplus"],
     []),

    # Chapter 6
    ("firm", "ch6", "Firm",
     "An organization that hires factors of production and uses them to produce and sell goods or services.",
     "A bakery, a hospital, and a software studio are all firms.",
     ["production-function", "economic-profit"],
     []),
    ("production-function", "ch6", "Production function",
     "The relationship between the quantity of inputs a firm uses and the quantity of output it can produce.",
     "Two ovens and three bakers might produce 200 loaves a day.",
     ["marginal-product", "factors-of-production"],
     []),
    ("marginal-product", "ch6", "Marginal product",
     "The extra output produced by one additional unit of an input, holding other inputs fixed.",
     "The fifth barista might add 12 drinks an hour to output.",
     ["diminishing-marginal-returns", "production-function", "mrp"],
     ["MP", "marginal product of labor"]),
    ("diminishing-marginal-returns", "ch6", "Diminishing marginal returns",
     "In the short run, adding more of one input while holding others fixed eventually yields smaller extra output.",
     "Crowding a fifth cook into a tiny kitchen adds less output than the second cook did.",
     ["marginal-product", "short-run"],
     ["diminishing returns", "law of diminishing returns"]),
    ("explicit-cost", "ch6", "Explicit cost",
     "A cost that involves a direct money outlay.",
     "Wages, rent, and flour invoices are explicit costs.",
     ["implicit-cost", "accounting-profit", "economic-profit"],
     []),
    ("implicit-cost", "ch6", "Implicit cost",
     "The opportunity cost of using resources the firm already owns, including the owner's time and capital.",
     "The salary an owner forgoes by running their own shop is an implicit cost.",
     ["explicit-cost", "opportunity-cost", "economic-profit"],
     []),
    ("accounting-profit", "ch6", "Accounting profit",
     "Total revenue minus explicit costs. It ignores implicit costs.",
     "Revenue of $200,000 minus $160,000 of bills is $40,000 of accounting profit.",
     ["economic-profit", "explicit-cost"],
     []),
    ("economic-profit", "ch6", "Economic profit",
     "Total revenue minus all opportunity costs, explicit and implicit. Zero economic profit means the firm is earning a normal return.",
     "If the same $40,000 accounting profit requires giving up a $50,000 job, economic profit is negative.",
     ["accounting-profit", "implicit-cost", "normal-profit"],
     []),
    ("normal-profit", "ch6", "Normal profit",
     "The minimum return needed to keep resources in their current use; equivalent to zero economic profit.",
     "A cafe that covers wages, rent, and the owner's next-best salary is earning normal profit.",
     ["economic-profit", "implicit-cost"],
     []),
    ("fixed-cost", "ch6", "Fixed cost",
     "A cost that does not change with output in the short run.",
     "Monthly shop rent is a fixed cost whether you bake 10 loaves or 1,000.",
     ["variable-cost", "total-cost", "average-fixed-cost"],
     ["FC"]),
    ("variable-cost", "ch6", "Variable cost",
     "A cost that changes with output.",
     "Flour and hourly wages rise as a bakery produces more bread.",
     ["fixed-cost", "total-cost", "average-variable-cost"],
     ["VC"]),
    ("total-cost", "ch6", "Total cost",
     "Fixed cost plus variable cost.",
     "If rent is $2,000 and ingredients plus wages are $3,000, total cost is $5,000.",
     ["fixed-cost", "variable-cost", "average-total-cost"],
     ["TC"]),
    ("mc", "ch6", "Marginal cost (firm)",
     "The extra cost of producing one more unit of output. MC typically falls at first and then rises because of diminishing returns.",
     "The 101st sandwich might add $2.40 of ingredients and extra labor.",
     ["average-total-cost", "diminishing-marginal-returns", "mr-equals-mc"],
     ["marginal cost"]),
    ("average-total-cost", "ch6", "Average total cost",
     "Total cost divided by output. ATC is U-shaped in the usual short-run model.",
     "Producing 500 mugs at $2,000 total cost means ATC is $4.",
     ["average-variable-cost", "average-fixed-cost", "mc"],
     ["ATC", "average cost", "AC"]),
    ("average-variable-cost", "ch6", "Average variable cost",
     "Variable cost divided by output. A competitive firm shuts down in the short run if price falls below AVC.",
     "If variable costs are $300 for 100 units, AVC is $3.",
     ["average-total-cost", "shutdown-rule"],
     ["AVC"]),
    ("average-fixed-cost", "ch6", "Average fixed cost",
     "Fixed cost divided by output. AFC falls as output rises because the same fixed cost is spread over more units.",
     "A $1,000 oven used for 500 pizzas contributes $2 of AFC per pizza.",
     ["fixed-cost", "average-total-cost"],
     ["AFC"]),
    ("short-run", "ch6", "Short run",
     "A period in which at least one input is fixed.",
     "A restaurant can hire waiters this week but cannot enlarge the dining room.",
     ["long-run", "fixed-cost", "diminishing-marginal-returns"],
     []),
    ("long-run", "ch6", "Long run",
     "A period in which all inputs can be varied and firms can enter or exit.",
     "Over several years a restaurant can move, expand, or close.",
     ["short-run", "economies-of-scale"],
     []),
    ("economies-of-scale", "ch6", "Economies of scale",
     "Long-run average cost falling as the firm's scale of production rises.",
     "A large chip plant may have a lower cost per chip than a tiny one.",
     ["diseconomies-of-scale", "constant-returns-to-scale", "natural-monopoly"],
     []),
    ("diseconomies-of-scale", "ch6", "Diseconomies of scale",
     "Long-run average cost rising as the firm becomes very large, often from coordination problems.",
     "A sprawling restaurant chain may add layers of management that raise cost per meal.",
     ["economies-of-scale", "long-run"],
     []),
    ("constant-returns-to-scale", "ch6", "Constant returns to scale",
     "Long-run average cost that stays the same as the firm scales up or down.",
     "Duplicating a successful coffee kiosk in a similar location may leave average cost unchanged.",
     ["economies-of-scale", "diseconomies-of-scale"],
     ["CRS"]),

    # Chapter 7
    ("perfect-competition", "ch7", "Perfect competition",
     "A market structure with many firms, a standardized product, free entry, and firms that are price takers. In long-run equilibrium, economic profit is zero and price equals minimum ATC.",
     "Small organic-egg farms selling into a large wholesale market are close to this model.",
     ["price-taker", "mr-equals-mc", "economic-profit"],
     ["perfectly competitive market"]),
    ("price-taker", "ch7", "Price taker",
     "A buyer or seller who must accept the market price and cannot influence it.",
     "A single soybean farmer takes the world price as given.",
     ["perfect-competition", "competitive-market", "price-maker"],
     []),
    ("price-maker", "ch7", "Price maker",
     "A seller with market power that can choose price, facing a downward-sloping demand curve.",
     "A patented drug firm can set a high price because rivals cannot legally copy the drug.",
     ["monopoly", "price-taker", "market-power"],
     []),
    ("market-power", "ch7", "Market power",
     "The ability to set price above marginal cost without losing all customers.",
     "A town's only internet provider has market power if residents have no alternative.",
     ["price-maker", "monopoly", "barriers-to-entry"],
     []),
    ("monopoly", "ch7", "Monopoly",
     "A market with a single seller of a product that has no close substitutes, protected by barriers to entry. The monopolist produces where MR = MC and charges the price on the demand curve.",
     "A regional water utility is often a regulated monopoly.",
     ["barriers-to-entry", "natural-monopoly", "price-discrimination", "mr-equals-mc"],
     []),
    ("barriers-to-entry", "ch7", "Barriers to entry",
     "Obstacles that prevent new firms from competing, such as patents, licenses, control of a key input, or large economies of scale.",
     "A patent on a drug is a legal barrier to entry.",
     ["monopoly", "natural-monopoly", "market-power"],
     []),
    ("natural-monopoly", "ch7", "Natural monopoly",
     "An industry in which one firm can supply the market at a lower average cost than two or more firms, usually because of large fixed costs and economies of scale.",
     "Electricity transmission is a classic natural monopoly.",
     ["economies-of-scale", "monopoly", "barriers-to-entry"],
     []),
    ("price-discrimination", "ch7", "Price discrimination",
     "Selling the same product to different buyers at different prices that are not justified by cost differences.",
     "Student discounts and airline fare classes are forms of price discrimination.",
     ["monopoly", "consumer-surplus"],
     []),
    ("mr-equals-mc", "ch7", "MR = MC rule",
     "A profit-maximizing firm produces the quantity at which marginal revenue equals marginal cost, provided price covers the relevant average cost.",
     "If another haircut would add $20 of revenue and $14 of cost, the salon should offer it.",
     ["marginal-revenue", "mc", "shutdown-rule"],
     ["profit maximization", "MR = MC"]),
    ("marginal-revenue", "ch7", "Marginal revenue",
     "The extra revenue from selling one more unit. For a price taker, MR equals price. For a price maker, MR is below price because selling more requires cutting price on previous units.",
     "A monopolist who cuts price from $10 to $9 to sell an extra unit may gain $9 but lose $1 on each previous unit.",
     ["mr-equals-mc", "monopoly"],
     ["MR"]),
    ("shutdown-rule", "ch7", "Shutdown rule",
     "In the short run a firm should produce nothing if price is below average variable cost. It should still operate at a loss if price is between AVC and ATC, because some fixed costs are covered.",
     "A ski lodge may close for a week of rain if ticket revenue cannot cover staff and fuel.",
     ["average-variable-cost", "sunk-cost", "perfect-competition"],
     []),
    ("oligopoly", "ch7", "Oligopoly",
     "A market dominated by a few firms that are interdependent: each firm's best action depends on what the others do.",
     "The markets for airframes, wireless carriers, and soda are often oligopolies.",
     ["game-theory", "nash-equilibrium", "cartel", "collusion"],
     []),
    ("monopolistic-competition", "ch7", "Monopolistic competition",
     "A market with many firms, free entry, and differentiated products. Firms have some price-setting power but earn zero economic profit in the long run.",
     "Neighborhood restaurants and paperback novels are monopolistically competitive.",
     ["product-differentiation", "perfect-competition", "monopoly"],
     []),
    ("product-differentiation", "ch7", "Product differentiation",
     "Making a product distinct in quality, branding, location, or features so that it is not a perfect substitute for rivals' goods.",
     "Two coffee shops a block apart differentiate with vibe, roast, and hours.",
     ["monopolistic-competition"],
     []),
    ("game-theory", "ch7", "Game theory",
     "The study of strategic interaction, in which each player's payoff depends on everyone else's actions.",
     "Two gas stations choosing prices are playing a pricing game.",
     ["nash-equilibrium", "oligopoly", "collusion"],
     []),
    ("nash-equilibrium", "ch7", "Nash equilibrium",
     "A strategy profile in which no player wants to change their action given what the others are doing.",
     "If both firms advertise because each would lose customers by stopping alone, that pair of choices can be a Nash equilibrium.",
     ["game-theory", "oligopoly"],
     []),
    ("collusion", "ch7", "Collusion",
     "An agreement among firms to limit competition, for example by fixing prices or splitting markets. Collusion is often illegal.",
     "Rival airlines secretly agreeing not to cut fares is collusion.",
     ["cartel", "oligopoly"],
     []),
    ("cartel", "ch7", "Cartel",
     "A group of firms that collude to act like a monopolist, typically by restricting output to raise price.",
     "OPEC is a well-known oil cartel, though members often have incentives to cheat.",
     ["collusion", "oligopoly", "nash-equilibrium"],
     []),

    # Chapter 8
    ("derived-demand", "ch8", "Derived demand",
     "Demand for a factor of production that comes from the demand for the goods that factor helps produce.",
     "Demand for carpenters rises when demand for new houses rises.",
     ["mrp", "factors-of-production"],
     []),
    ("mrp", "ch8", "Marginal revenue product",
     "The extra revenue from employing one more unit of a factor: marginal product times marginal revenue.",
     "If one more programmer adds software that sells for $4,000 of extra revenue, MRP is $4,000.",
     ["derived-demand", "marginal-product", "wage"],
     ["MRP", "value of marginal product", "VMP"]),
    ("wage", "ch8", "Wage",
     "The price of labor services, usually per hour or per year.",
     "A cafe may pay $18 an hour plus tips.",
     ["labor-supply", "human-capital", "compensating-differential"],
     []),
    ("labor-supply", "ch8", "Labor supply",
     "The relationship between the wage and the hours of work people are willing to offer. Higher wages have substitution and income effects that can pull in opposite directions.",
     "A higher wage may lead some people to work more and others to take more leisure.",
     ["wage", "human-capital"],
     []),
    ("human-capital", "ch8", "Human capital",
     "The skills, knowledge, and health embodied in people that raise their productivity.",
     "A nursing degree is human capital that typically raises wages.",
     ["physical-capital", "productivity", "wage"],
     []),
    ("compensating-differential", "ch8", "Compensating differential",
     "An extra wage paid to attract workers to jobs that are unpleasant, risky, or inconvenient.",
     "Night-shift and offshore-rig pay often includes a compensating differential.",
     ["wage", "human-capital"],
     []),
    ("monopsony", "ch8", "Monopsony",
     "A market with a single (or dominant) buyer. A labor monopsonist hires fewer workers and pays a lower wage than a competitive labor market.",
     "A remote mining town with one large employer can be a labor monopsony.",
     ["monopoly", "wage"],
     []),
    ("physical-capital", "ch8", "Physical capital",
     "Produced goods used to produce other goods and services, such as machines, buildings, and tools.",
     "A CNC mill and a warehouse are physical capital.",
     ["human-capital", "investment", "factors-of-production"],
     ["capital"]),
    ("land", "ch8", "Land",
     "Natural resources used in production, including soil, minerals, water, and location.",
     "A vineyard's hillside is land in the economic sense.",
     ["rent", "factors-of-production"],
     []),
    ("rent", "ch8", "Economic rent",
     "A payment to a factor above the minimum needed to keep it in its current use. Also, the return to land.",
     "A pop star's income far above their next-best job is mostly economic rent.",
     ["land", "opportunity-cost"],
     ["rent"]),
    ("interest", "ch8", "Interest",
     "The return to saving and the price of borrowed funds, usually expressed as a percentage per year.",
     "A 5% interest rate means $100 saved grows to $105 in a year, before inflation.",
     ["real-interest-rate", "investment", "physical-capital"],
     []),

    # Chapter 9
    ("market-failure", "ch9", "Market failure",
     "A situation in which an unregulated market fails to allocate resources efficiently.",
     "Pollution, unprovided street lighting, and lemons markets are standard market failures.",
     ["externality", "public-good", "asymmetric-information"],
     []),
    ("externality", "ch9", "Externality",
     "A cost or benefit of an activity that falls on a bystander who did not choose to incur it.",
     "Your neighbor's late-night drum practice is a negative externality for you.",
     ["negative-externality", "positive-externality", "pigouvian-tax"],
     []),
    ("negative-externality", "ch9", "Negative externality",
     "An external cost. The market quantity is too high because sellers and buyers ignore costs imposed on others.",
     "Factory smoke that harms nearby lungs is a negative externality.",
     ["externality", "pigouvian-tax", "deadweight-loss"],
     []),
    ("positive-externality", "ch9", "Positive externality",
     "An external benefit. The market quantity is too low because decision makers ignore benefits conferred on others.",
     "Flu shots protect people who never got vaccinated.",
     ["externality", "subsidy"],
     []),
    ("pigouvian-tax", "ch9", "Pigouvian tax",
     "A tax equal to the marginal external cost, meant to make private decision makers face the social cost.",
     "A carbon tax is a Pigouvian tax on greenhouse-gas emissions.",
     ["negative-externality", "subsidy"],
     ["Pigovian tax", "corrective tax"]),
    ("subsidy", "ch9", "Subsidy",
     "A payment that lowers the cost of an activity. A subsidy equal to a marginal external benefit can correct a positive externality.",
     "Scholarships subsidize education, which may have social benefits beyond the student.",
     ["positive-externality", "pigouvian-tax"],
     []),
    ("coase-theorem", "ch9", "Coase theorem",
     "If property rights are well defined and bargaining is costless, private parties can negotiate an efficient solution to an externality regardless of who has the legal right.",
     "A beekeeper and an orchard owner can contract over hive placement if talking is cheap.",
     ["externality", "market-failure"],
     []),
    ("public-good", "ch9", "Public good",
     "A good that is nonrival and nonexcludable. Markets underprovide public goods because of the free-rider problem.",
     "Basic scientific knowledge and national defense are classic public goods.",
     ["private-good", "free-rider", "common-resource", "club-good"],
     []),
    ("private-good", "ch9", "Private good",
     "A good that is both rival and excludable, so markets can usually allocate it well.",
     "A sandwich is a private good: if you eat it, others cannot, and the shop can charge you.",
     ["public-good", "rivalry", "excludability"],
     []),
    ("common-resource", "ch9", "Common resource",
     "A good that is rival but nonexcludable. It is prone to overuse — the tragedy of the commons.",
     "An open-access fishery is a common resource.",
     ["tragedy-of-the-commons", "public-good", "rivalry"],
     ["common-pool resource"]),
    ("club-good", "ch9", "Club good",
     "A good that is nonrival (at least until congestion) but excludable.",
     "A streaming subscription or a toll road with spare capacity is a club good.",
     ["public-good", "private-good", "excludability"],
     ["artificially scarce good"]),
    ("rivalry", "ch9", "Rivalry",
     "A good is rival if one person's use reduces the amount available for others.",
     "A parking space is rival; a radio broadcast is not.",
     ["excludability", "private-good", "common-resource"],
     ["rival", "rivalrous"]),
    ("excludability", "ch9", "Excludability",
     "A good is excludable if people who do not pay can be prevented from using it.",
     "A movie theater can exclude nonpayers; a city fireworks show usually cannot.",
     ["rivalry", "public-good", "free-rider"],
     ["excludable"]),
    ("free-rider", "ch9", "Free rider",
     "Someone who enjoys a good without paying for it. Free riding undermines private provision of nonexcludable goods.",
     "A neighbor who enjoys a block's private security patrol without contributing is a free rider.",
     ["public-good", "excludability"],
     ["free-rider problem"]),
    ("tragedy-of-the-commons", "ch9", "Tragedy of the commons",
     "The overuse of a common resource when individuals do not bear the full social cost of their use.",
     "Open pasture that is overgrazed until the grass is gone is the original tragedy of the commons.",
     ["common-resource", "externality"],
     []),
    ("asymmetric-information", "ch9", "Asymmetric information",
     "A situation in which one party to a transaction knows more than the other.",
     "A used-car seller usually knows more about the car than the buyer.",
     ["adverse-selection", "moral-hazard", "market-failure"],
     []),
    ("adverse-selection", "ch9", "Adverse selection",
     "When hidden information before a deal means the mix of participants is worse than the average of the whole population.",
     "If only the sickest people buy health insurance, premiums rise and healthier people drop out.",
     ["asymmetric-information", "moral-hazard"],
     []),
    ("moral-hazard", "ch9", "Moral hazard",
     "When hidden actions after a deal lead someone to take more risk or less care because another party bears the cost.",
     "Insured drivers may park less carefully than they would if they paid every scratch themselves.",
     ["asymmetric-information", "adverse-selection"],
     []),
    ("price-ceiling", "ch9", "Price ceiling",
     "A legal maximum price. A ceiling below equilibrium is binding and creates a shortage.",
     "Rent control is a price ceiling in the housing market.",
     ["price-floor", "shortage", "deadweight-loss"],
     []),
    ("price-floor", "ch9", "Price floor",
     "A legal minimum price. A floor above equilibrium is binding and creates a surplus.",
     "A minimum wage is a price floor in the labor market.",
     ["price-ceiling", "surplus", "deadweight-loss"],
     []),
    ("deadweight-loss", "ch9", "Deadweight loss",
     "The fall in total surplus from an inefficient quantity — trades that should happen but do not, or trades that should not happen but do.",
     "A tax that stops mutually beneficial used-book sales creates deadweight loss.",
     ["total-surplus", "price-ceiling", "price-floor"],
     ["DWL"]),
    ("tax-incidence", "ch9", "Tax incidence",
     "The actual division of a tax burden between buyers and sellers, which depends on elasticities, not on who writes the check.",
     "A cigarette tax may fall mostly on buyers if demand is inelastic.",
     ["price-elasticity-of-demand", "price-elasticity-of-supply"],
     []),
    ("quota", "ch9", "Quota",
     "A legal limit on the quantity that may be bought, sold, or imported.",
     "A city that issues only 200 taxi medallions is using a quota.",
     ["deadweight-loss", "tariff"],
     ["quantity restriction"]),

    # Chapter 10
    ("gdp", "ch10", "Gross domestic product",
     "The market value of all final goods and services produced within a country in a given period.",
     "Cars assembled in the United States count in U.S. GDP even if the firm is foreign-owned.",
     ["nominal-gdp", "real-gdp", "gnp", "value-added"],
     ["GDP"]),
    ("nominal-gdp", "ch10", "Nominal GDP",
     "GDP measured in current prices, unadjusted for inflation.",
     "If prices and output both rise, nominal GDP rises for both reasons.",
     ["gdp", "real-gdp", "gdp-deflator"],
     []),
    ("real-gdp", "ch10", "Real GDP",
     "GDP measured using the prices of a base year, so that changes reflect quantities rather than inflation.",
     "Real GDP is the standard measure of an economy's production over time.",
     ["nominal-gdp", "gdp-deflator", "economic-growth"],
     []),
    ("gdp-deflator", "ch10", "GDP deflator",
     "A price index equal to nominal GDP divided by real GDP, times 100. It covers all goods in GDP, not just consumer goods.",
     "If nominal GDP is 110 and real GDP is 100, the deflator is 110.",
     ["nominal-gdp", "real-gdp", "cpi"],
     []),
    ("value-added", "ch10", "Value added",
     "The value of a firm's output minus the value of intermediate goods it buys. GDP equals the sum of value added across firms.",
     "A baker who buys $1 of flour and sells $4 of bread adds $3 of value.",
     ["gdp"],
     []),
    ("gnp", "ch10", "Gross national product",
     "The market value of final goods and services produced by a country's residents, including income earned abroad and excluding income earned by foreigners domestically.",
     "Wages a U.S. engineer earns on a project in Singapore count in U.S. GNP, not U.S. GDP.",
     ["gdp"],
     ["GNP"]),
    ("cpi", "ch10", "Consumer price index",
     "A measure of the cost of a fixed basket of goods and services bought by a typical household, relative to a base period.",
     "If the basket cost $200 in the base year and $260 now, the CPI is 130.",
     ["inflation", "gdp-deflator"],
     ["CPI"]),
    ("inflation", "ch10", "Inflation",
     "A sustained rise in the general price level, usually measured as the percentage change in a price index.",
     "If the CPI rises from 200 to 206, the inflation rate is 3%.",
     ["cpi", "deflation", "inflation-rate"],
     []),
    ("inflation-rate", "ch10", "Inflation rate",
     "The percentage change in a price index from one period to the next.",
     "(This year's CPI − last year's CPI) / last year's CPI × 100.",
     ["inflation", "cpi"],
     []),
    ("deflation", "ch10", "Deflation",
     "A sustained fall in the general price level.",
     "Japan experienced stretches of deflation in the 1990s and 2000s.",
     ["inflation", "hyperinflation"],
     []),
    ("labor-force", "ch10", "Labor force",
     "The sum of employed and unemployed people who are actively seeking work. People not looking for work are outside the labor force.",
     "A full-time student who is not job hunting is not in the labor force.",
     ["unemployment-rate", "discouraged-worker"],
     []),
    ("unemployment-rate", "ch10", "Unemployment rate",
     "The percentage of the labor force that is unemployed: unemployed / labor force × 100.",
     "If 8 million people are unemployed and the labor force is 160 million, the rate is 5%.",
     ["labor-force", "frictional-unemployment", "structural-unemployment", "cyclical-unemployment"],
     []),
    ("frictional-unemployment", "ch10", "Frictional unemployment",
     "Short-term unemployment that arises from job search, matching, and normal turnover.",
     "A recent graduate interviewing for a first job is frictionally unemployed.",
     ["structural-unemployment", "natural-rate-of-unemployment"],
     []),
    ("structural-unemployment", "ch10", "Structural unemployment",
     "Unemployment that arises from a mismatch between workers' skills or locations and the jobs available, or from labor-market institutions that keep wages above equilibrium.",
     "Coal miners in a region where mines have closed may be structurally unemployed.",
     ["frictional-unemployment", "natural-rate-of-unemployment"],
     []),
    ("cyclical-unemployment", "ch10", "Cyclical unemployment",
     "Unemployment above the natural rate that is caused by a downturn in the business cycle.",
     "Layoffs during a recession are mostly cyclical unemployment.",
     ["business-cycle", "natural-rate-of-unemployment", "recession"],
     []),
    ("natural-rate-of-unemployment", "ch10", "Natural rate of unemployment",
     "The unemployment rate when the economy is at potential output: frictional plus structural unemployment, with cyclical unemployment at zero.",
     "Policy that shortens job search can lower the natural rate.",
     ["frictional-unemployment", "structural-unemployment", "potential-output"],
     ["NAIRU", "natural unemployment"]),
    ("discouraged-worker", "ch10", "Discouraged worker",
     "Someone who wants a job but has stopped looking because they believe none are available. Discouraged workers are not counted as unemployed.",
     "A long-term job seeker who quits applying drops out of the official unemployment rate.",
     ["labor-force", "unemployment-rate"],
     []),
    ("business-cycle", "ch10", "Business cycle",
     "The irregular short-run fluctuation of aggregate economic activity around its long-run trend, with expansions and recessions.",
     "Output, employment, and investment typically rise together in expansions and fall in recessions.",
     ["recession", "expansion", "potential-output"],
     []),
    ("recession", "ch10", "Recession",
     "A significant, widespread decline in economic activity lasting more than a few months.",
     "The 2008–09 downturn was a deep recession in many countries.",
     ["expansion", "business-cycle", "cyclical-unemployment"],
     []),
    ("expansion", "ch10", "Expansion",
     "A period of rising real GDP and usually falling unemployment, from a trough to a peak.",
     "The long expansion of the 2010s followed the Great Recession.",
     ["recession", "business-cycle"],
     ["recovery"]),

    # Chapter 11
    ("economic-growth", "ch11", "Economic growth",
     "A sustained increase in real GDP per person, which raises average living standards over time.",
     "Real GDP per person in many rich countries is many times higher than a century ago.",
     ["productivity", "real-gdp", "rule-of-70"],
     []),
    ("productivity", "ch11", "Productivity",
     "Output per unit of input, most often output per hour of labor.",
     "A barista who makes 20 drinks an hour is more productive than one who makes 10, other things equal.",
     ["human-capital", "physical-capital", "technological-progress"],
     ["labor productivity"]),
    ("technological-progress", "ch11", "Technological progress",
     "Advances in knowledge that let the same inputs produce more or better output.",
     "Container shipping and semiconductors raised productivity across many industries.",
     ["productivity", "economic-growth"],
     ["technology"]),
    ("catch-up-effect", "ch11", "Catch-up effect",
     "The tendency for poorer countries to grow faster than richer ones when they can adopt existing technology and when extra capital is very productive.",
     "South Korea grew rapidly in the late 20th century as it industrialized and imported techniques.",
     ["economic-growth", "diminishing-returns-to-capital"],
     ["convergence"]),
    ("diminishing-returns-to-capital", "ch11", "Diminishing returns to capital",
     "Holding technology and labor fixed, extra machines eventually add less and less extra output. This is why capital accumulation alone cannot sustain growth forever.",
     "Giving a second computer to an office already full of computers helps less than giving the first computer.",
     ["physical-capital", "technological-progress", "catch-up-effect"],
     []),
    ("institutions", "ch11", "Institutions",
     "The formal and informal rules that shape economic life, including property rights, courts, and political stability. Growth research treats them as a deep cause of prosperity.",
     "Secure title to land makes farmers more willing to invest in irrigation.",
     ["property-rights", "economic-growth"],
     []),
    ("property-rights", "ch11", "Property rights",
     "The legal ability to own, use, and transfer assets, and to enforce those claims. Weak property rights discourage investment and growth.",
     "A firm will not build a factory if it expects the plant to be seized.",
     ["institutions", "economic-growth"],
     []),
    ("saving", "ch11", "Saving",
     "Income that is not consumed. In a closed economy, saving finances investment.",
     "A household that earns $60,000 and spends $52,000 saves $8,000.",
     ["investment", "crowding-out"],
     []),
    ("investment", "ch11", "Investment",
     "Spending on new capital goods — plant, equipment, housing, and inventories — not the purchase of financial assets.",
     "Buying a newly built apartment is investment; buying an old stock certificate is not.",
     ["saving", "physical-capital", "crowding-out"],
     ["gross investment"]),
    ("rule-of-70", "ch11", "Rule of 70",
     "A shortcut: the number of years for a growing variable to double is about 70 divided by the annual growth rate in percent.",
     "At 2% growth, living standards double in about 35 years; at 7%, in about 10 years.",
     ["economic-growth"],
     ["rule of 72"]),

    # Chapter 12
    ("money", "ch12", "Money",
     "The widely accepted medium of exchange, and usually also a unit of account and store of value.",
     "Dollar bills and checking deposits are money in the United States; houses are not, because they are not a medium of exchange.",
     ["medium-of-exchange", "unit-of-account", "store-of-value", "liquidity"],
     []),
    ("medium-of-exchange", "ch12", "Medium of exchange",
     "An item that buyers give to sellers when they purchase goods and services, eliminating the need for barter.",
     "You pay for groceries with a card that draws on a deposit, not with a haircut.",
     ["money", "unit-of-account", "store-of-value"],
     []),
    ("unit-of-account", "ch12", "Unit of account",
     "The yardstick in which prices and debts are recorded.",
     "Menus list prices in dollars, not in minutes of work.",
     ["money", "medium-of-exchange"],
     []),
    ("store-of-value", "ch12", "Store of value",
     "An item that can transfer purchasing power from the present to the future. Inflation erodes money's usefulness as a store of value.",
     "Cash under a mattress stores value poorly during high inflation.",
     ["money", "inflation"],
     []),
    ("liquidity", "ch12", "Liquidity",
     "The ease with which an asset can be converted into the medium of exchange without a large loss of value.",
     "Cash is perfectly liquid; a house is much less liquid.",
     ["money", "m1", "m2"],
     []),
    ("commodity-money", "ch12", "Commodity money",
     "Money that has intrinsic value as a good, such as gold coins or cigarettes in a prison camp.",
     "Gold coins could be melted for jewelry, so they had value beyond being money.",
     ["fiat-money", "money"],
     []),
    ("fiat-money", "ch12", "Fiat money",
     "Money with no intrinsic value that is money by government decree and social acceptance.",
     "Modern paper currency and central-bank reserves are fiat money.",
     ["commodity-money", "money"],
     []),
    ("m1", "ch12", "M1",
     "A narrow money-stock measure that includes currency in circulation and highly liquid deposits such as checking accounts.",
     "The cash in your wallet plus your checking balance are in M1.",
     ["m2", "money", "liquidity"],
     []),
    ("m2", "ch12", "M2",
     "A broader money-stock measure: M1 plus less liquid deposits such as ordinary savings accounts and small time deposits.",
     "A savings account is typically in M2 but not always treated as immediately spendable as cash.",
     ["m1", "money"],
     []),
    ("central-bank", "ch12", "Central bank",
     "The institution that manages a country's money and monetary policy, often including bank supervision and the payments system.",
     "The Federal Reserve is the central bank of the United States.",
     ["monetary-policy", "open-market-operations", "money-supply"],
     ["the Fed"]),
    ("fractional-reserve-banking", "ch12", "Fractional-reserve banking",
     "A system in which banks hold only a fraction of deposits as reserves and lend the rest, which creates additional deposits.",
     "A bank that keeps 10% of deposits in reserve can lend the other 90%.",
     ["reserve-ratio", "money-multiplier"],
     []),
    ("reserve-ratio", "ch12", "Reserve ratio",
     "The fraction of deposits that a bank holds as reserves.",
     "A 10% reserve ratio means $10 of reserves for every $100 of deposits.",
     ["fractional-reserve-banking", "money-multiplier"],
     ["reserve requirement"]),
    ("money-multiplier", "ch12", "Money multiplier",
     "The maximum factor by which an injection of reserves can increase the money stock in a simple reserve-ratio model, equal to 1 / reserve ratio.",
     "With a 10% reserve ratio, the simple multiplier is 10.",
     ["reserve-ratio", "fractional-reserve-banking"],
     []),
    ("money-supply", "ch12", "Money supply",
     "The quantity of money available in the economy, measured by aggregates such as M1 or M2.",
     "Central banks influence the money supply through policy tools.",
     ["m1", "m2", "monetary-policy"],
     ["money stock"]),
    ("quantity-theory-of-money", "ch12", "Quantity theory of money",
     "The view that, in the long run, the price level is proportional to the money supply. In the equation MV = PY, if V and Y are stable, more M means a higher P.",
     "Historical hyperinflations were accompanied by explosive growth in the money stock.",
     ["velocity", "inflation", "classical-dichotomy"],
     ["quantity equation"]),
    ("velocity", "ch12", "Velocity of money",
     "The average number of times a unit of money is spent on final goods and services in a period. In MV = PY, V = PY / M.",
     "If people hold cash longer, velocity falls.",
     ["quantity-theory-of-money"],
     ["V"]),
    ("fisher-effect", "ch12", "Fisher effect",
     "The one-for-one long-run relationship between expected inflation and the nominal interest rate: nominal rate ≈ real rate + expected inflation.",
     "If expected inflation rises from 2% to 5% and the real rate is unchanged, nominal rates tend to rise by 3 points.",
     ["real-interest-rate", "inflation"],
     []),
    ("real-interest-rate", "ch12", "Real interest rate",
     "The interest rate adjusted for inflation: nominal interest rate minus the inflation rate. It measures the real cost of borrowing and the real return to saving.",
     "A 6% loan with 4% inflation has a 2% real interest rate.",
     ["interest", "fisher-effect", "inflation"],
     ["real rate"]),
    ("hyperinflation", "ch12", "Hyperinflation",
     "Extremely rapid inflation, often defined as monthly price increases of 50% or more, usually caused by massive money creation.",
     "Germany in 1923 and Zimbabwe in the 2000s are textbook hyperinflations.",
     ["inflation", "quantity-theory-of-money"],
     []),
    ("menu-costs", "ch12", "Menu costs",
     "The real costs of changing posted prices, one reason prices can be sticky.",
     "A restaurant reprinting menus after every price change incurs menu costs.",
     ["sticky-prices", "inflation"],
     []),
    ("shoeleather-costs", "ch12", "Shoeleather costs",
     "The time and effort people spend to economize on money holdings when inflation is high.",
     "During high inflation, people make many small withdrawals instead of holding cash.",
     ["inflation", "money"],
     ["shoe-leather costs"]),

    # Chapter 13
    ("aggregate-demand", "ch13", "Aggregate demand",
     "The total quantity of goods and services demanded in the economy at each price level: C + I + G + NX.",
     "A stock-market boom that raises consumption shifts AD right.",
     ["aggregate-supply", "net-exports", "multiplier"],
     ["AD"]),
    ("aggregate-supply", "ch13", "Aggregate supply",
     "The total quantity of goods and services firms produce at each price level. Distinguish the sticky-price short run from the flexible-price long run.",
     "A sudden oil-price spike can shift short-run aggregate supply left.",
     ["sras", "lras", "aggregate-demand"],
     ["AS"]),
    ("sras", "ch13", "Short-run aggregate supply",
     "The upward-sloping AS relationship when some wages or prices are sticky, so a higher price level raises output temporarily.",
     "If demand jumps and wages have not yet adjusted, firms produce more.",
     ["lras", "sticky-wages", "sticky-prices"],
     ["SRAS"]),
    ("lras", "ch13", "Long-run aggregate supply",
     "A vertical AS curve at potential output, determined by labor, capital, and technology, not by the price level.",
     "Immigration that expands the labor force shifts LRAS right.",
     ["potential-output", "sras", "classical-dichotomy"],
     ["LRAS"]),
    ("potential-output", "ch13", "Potential output",
     "The level of real GDP the economy can produce when labor and capital are used at normal intensity and unemployment is at the natural rate. Also called natural or full-employment output.",
     "A hurricane that destroys factories lowers potential output until they are rebuilt.",
     ["lras", "output-gap", "natural-rate-of-unemployment"],
     ["natural output", "full-employment output", "Y*"]),
    ("output-gap", "ch13", "Output gap",
     "Actual real GDP minus potential output. A negative gap is a recessionary gap; a positive gap is an inflationary gap.",
     "If potential is 20 trillion and actual is 19 trillion, the output gap is −1 trillion.",
     ["potential-output", "recession", "cyclical-unemployment"],
     ["recessionary gap", "inflationary gap"]),
    ("sticky-wages", "ch13", "Sticky wages",
     "Wages that adjust slowly, so a fall in demand can raise real wages temporarily and cause unemployment.",
     "Multi-year union contracts keep nominal wages from falling quickly in a slump.",
     ["sticky-prices", "sras", "unemployment-rate"],
     []),
    ("sticky-prices", "ch13", "Sticky prices",
     "Prices that adjust slowly because of menu costs, contracts, or customer relationships.",
     "Magazine cover prices used to stay fixed for years.",
     ["menu-costs", "sticky-wages", "sras"],
     []),
    ("demand-shock", "ch13", "Demand shock",
     "A sudden shift of aggregate demand, from changes in confidence, wealth, policy, or the rest of the world.",
     "A collapse in housing wealth can be a negative demand shock.",
     ["supply-shock", "aggregate-demand"],
     []),
    ("supply-shock", "ch13", "Supply shock",
     "A sudden shift of aggregate supply, often from input prices or productivity.",
     "A pandemic that closes factories is a negative supply shock.",
     ["demand-shock", "stagflation", "sras"],
     []),
    ("stagflation", "ch13", "Stagflation",
     "The combination of high or rising inflation and weak output or high unemployment, typically from an adverse supply shock.",
     "The 1970s oil shocks produced stagflation in many advanced economies.",
     ["supply-shock", "inflation", "recession"],
     []),
    ("classical-dichotomy", "ch13", "Classical dichotomy",
     "The idea that, in the long run, real variables (output, real wages) are determined by real factors, while nominal variables (the price level, money) are determined by the money supply.",
     "Printing more money does not, by itself, create more factories in the long run.",
     ["quantity-theory-of-money", "lras"],
     []),

    # Chapter 14
    ("fiscal-policy", "ch14", "Fiscal policy",
     "The use of government spending and taxation to influence the economy.",
     "A temporary income-tax cut is expansionary fiscal policy.",
     ["monetary-policy", "multiplier", "automatic-stabilizers", "budget-deficit"],
     []),
    ("monetary-policy", "ch14", "Monetary policy",
     "Central-bank actions that influence money, credit, and interest rates to affect inflation and output.",
     "Cutting the policy interest rate is expansionary monetary policy.",
     ["fiscal-policy", "open-market-operations", "central-bank"],
     []),
    ("multiplier", "ch14", "Multiplier",
     "The factor by which a change in autonomous spending changes equilibrium output. In the simple Keynesian model it equals 1 / (1 − MPC).",
     "If MPC is 0.8, a $1 billion rise in government spending can raise output by $5 billion before crowding out and imports.",
     ["mpc", "fiscal-policy", "aggregate-demand"],
     ["spending multiplier"]),
    ("mpc", "ch14", "Marginal propensity to consume",
     "The fraction of an extra dollar of disposable income that households spend on consumption.",
     "If you spend 75 cents of each extra dollar, your MPC is 0.75.",
     ["multiplier", "saving"],
     ["MPC"]),
    ("automatic-stabilizers", "ch14", "Automatic stabilizers",
     "Taxes and transfers that reduce the size of fluctuations without new legislation. They raise deficits in slumps and shrink them in booms.",
     "Unemployment insurance and a progressive income tax are automatic stabilizers.",
     ["fiscal-policy", "budget-deficit"],
     []),
    ("budget-deficit", "ch14", "Budget deficit",
     "The amount by which government spending exceeds tax revenue in a period.",
     "If spending is $4.2 trillion and revenue is $3.8 trillion, the deficit is $0.4 trillion.",
     ["budget-surplus", "crowding-out", "fiscal-policy"],
     []),
    ("budget-surplus", "ch14", "Budget surplus",
     "The amount by which tax revenue exceeds government spending in a period.",
     "A booming economy can swing the budget into surplus even without new laws.",
     ["budget-deficit", "automatic-stabilizers"],
     []),
    ("crowding-out", "ch14", "Crowding out",
     "The reduction in private investment (or net exports) that can follow expansionary fiscal policy when interest rates or the exchange rate rise.",
     "Large government borrowing can push up interest rates and discourage firms from building plants.",
     ["investment", "budget-deficit", "fiscal-policy"],
     []),
    ("open-market-operations", "ch14", "Open-market operations",
     "Central-bank purchases or sales of securities used to change reserves and influence interest rates.",
     "The Fed buying Treasury securities injects reserves into the banking system.",
     ["monetary-policy", "central-bank", "money-supply"],
     ["OMO"]),
    ("discount-rate", "ch14", "Discount rate",
     "The interest rate a central bank charges commercial banks for borrowing reserves from the discount window.",
     "A lower discount rate makes it cheaper for banks to borrow from the Fed.",
     ["monetary-policy", "reserve-ratio"],
     []),
    ("inflation-targeting", "ch14", "Inflation targeting",
     "A monetary-policy regime in which the central bank announces and aims at a numerical inflation objective.",
     "Many central banks target inflation near 2%.",
     ["monetary-policy", "central-bank", "inflation"],
     []),
    ("liquidity-trap", "ch14", "Liquidity trap",
     "A situation in which the policy interest rate is near zero and further conventional monetary easing has little effect because people are willing to hold extra money.",
     "After 2008, several central banks hit the zero lower bound and turned to unconventional tools.",
     ["monetary-policy", "interest"],
     ["zero lower bound"]),
    ("phillips-curve", "ch14", "Phillips curve",
     "An observed short-run trade-off between inflation and unemployment. In the long run the curve is vertical at the natural rate if expectations adjust.",
     "Unexpectedly tight policy can raise unemployment while lowering inflation for a time.",
     ["inflation", "natural-rate-of-unemployment", "monetary-policy"],
     []),

    # Chapter 15
    ("net-exports", "ch15", "Net exports",
     "Exports minus imports. Also called the trade balance in goods and services.",
     "If a country exports $300 billion and imports $400 billion, net exports are −$100 billion.",
     ["exports", "imports", "current-account"],
     ["NX", "trade balance"]),
    ("current-account", "ch15", "Current account",
     "The record of trade in goods and services, net income from abroad, and net unilateral transfers.",
     "A current-account deficit means the country is a net borrower from the rest of the world.",
     ["capital-account", "net-exports"],
     []),
    ("capital-account", "ch15", "Capital and financial account",
     "The record of international purchases and sales of assets. A current-account deficit is matched by a financial-account surplus (net capital inflow).",
     "Foreigners buying domestic bonds are a capital inflow.",
     ["current-account", "capital-flight"],
     ["financial account"]),
    ("exchange-rate", "ch15", "Exchange rate",
     "The price of one currency in terms of another.",
     "If $1 buys ¥150, the dollar-yen exchange rate is 150 yen per dollar.",
     ["appreciation", "depreciation", "real-exchange-rate"],
     ["nominal exchange rate"]),
    ("appreciation", "ch15", "Appreciation",
     "A rise in the value of a currency: it buys more of another currency. Appreciation makes imports cheaper and exports less competitive.",
     "If the euro goes from $1.05 to $1.15, the euro has appreciated.",
     ["depreciation", "exchange-rate", "net-exports"],
     []),
    ("depreciation", "ch15", "Depreciation",
     "A fall in the value of a currency: it buys less of another currency. Depreciation makes exports cheaper to foreigners and imports more expensive at home.",
     "If the pound falls from $1.30 to $1.20, the pound has depreciated.",
     ["appreciation", "exchange-rate", "net-exports"],
     []),
    ("real-exchange-rate", "ch15", "Real exchange rate",
     "The relative price of domestic goods in terms of foreign goods: nominal exchange rate times domestic prices over foreign prices.",
     "If U.S. prices rise faster than foreign prices and the nominal rate is unchanged, U.S. goods become more expensive abroad.",
     ["exchange-rate", "purchasing-power-parity"],
     []),
    ("purchasing-power-parity", "ch15", "Purchasing-power parity",
     "The theory that a unit of currency should buy the same basket of goods everywhere, so the nominal exchange rate should reflect relative price levels. It is a long-run benchmark, not a short-run law.",
     "The Big Mac index is a playful PPP comparison.",
     ["real-exchange-rate", "exchange-rate"],
     ["PPP"]),
    ("tariff", "ch15", "Tariff",
     "A tax on imported goods. It usually raises the domestic price, reduces imports, and creates deadweight loss, while generating government revenue.",
     "A $500 tariff on each imported truck makes foreign trucks more expensive.",
     ["import-quota", "protectionism", "deadweight-loss"],
     []),
    ("import-quota", "ch15", "Import quota",
     "A quantitative limit on imports of a good. Like a tariff it restricts trade, but the scarcity rents often go to license holders rather than the government.",
     "A cap of 10,000 imported motorcycles a year is an import quota.",
     ["tariff", "quota", "protectionism"],
     []),
    ("protectionism", "ch15", "Protectionism",
     "Policies that restrict imports to shield domestic producers, such as tariffs, quotas, and local-content rules.",
     "\"Buy national\" rules for government contracts are a form of protectionism.",
     ["tariff", "import-quota", "gains-from-trade"],
     []),
    ("capital-flight", "ch15", "Capital flight",
     "A sudden large-scale movement of financial assets out of a country, often after a loss of confidence. It can depreciate the currency and raise domestic interest rates.",
     "Investors rushing to sell a country's bonds after a political crisis is capital flight.",
     ["capital-account", "depreciation", "exchange-rate"],
     []),
    ("floating-exchange-rate", "ch15", "Floating exchange rate",
     "A regime in which the currency's value is determined by market supply and demand, with little or no official peg.",
     "The dollar, euro, and yen float against one another.",
     ["fixed-exchange-rate", "exchange-rate"],
     ["flexible exchange rate"]),
    ("fixed-exchange-rate", "ch15", "Fixed exchange rate",
     "A regime in which the government or central bank pledges to keep the currency at a set value against another currency or basket, using reserves and policy to defend the peg.",
     "A small country may peg to the dollar to import monetary credibility.",
     ["floating-exchange-rate", "exchange-rate"],
     ["peg", "pegged exchange rate"]),
]


def main() -> None:
    out = []
    seen = set()
    for row in TERMS:
        tid, chapter, term, definition, example, related, aliases = row
        if tid in seen:
            raise SystemExit(f"duplicate id: {tid}")
        seen.add(tid)
        item = {
            "id": tid,
            "chapterId": chapter,
            "term": term,
            "definition": definition,
        }
        if example:
            item["example"] = example
        if related:
            item["related"] = related
        if aliases:
            item["aliases"] = aliases
        out.append(item)

    # Validate related ids exist
    for item in out:
        for rel in item.get("related", []):
            if rel not in seen:
                raise SystemExit(f"{item['id']} related unknown id: {rel}")

    dest = Path(__file__).resolve().parents[1] / "src" / "data" / "definitions.json"
    dest.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(out)} terms to {dest}")


if __name__ == "__main__":
    main()
